function [FractureHeightm, Times, Velocityms,FractureHeightFromSrcm] = importCSVResults2(filename, dataLines)
%IMPORTFILE1 Import data from a text file
%  [FRACTUREHEIGHTM, TIMES, VELOCITYMS] = IMPORTFILE1(FILENAME) reads
%  data from text file FILENAME for the default selection.  Returns the
%  data as column vectors.
%
%  [FRACTUREHEIGHTM, TIMES, VELOCITYMS] = IMPORTFILE1(FILE, DATALINES)
%  reads data for the specified row interval(s) of text file FILENAME.
%  Specify DATALINES as a positive scalar integer or a N-by-2 array of
%  positive scalar integers for dis-contiguous row intervals.
%
%  Example:
%  [FractureHeightm, Times, Velocityms] = importfile1("C:\Users\course\Documents\GitHub\EgerRiftBasics\AscentVelocity\PyFracResult1.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 25-Jun-2021 11:00:08

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 4);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["FractureHeightm", "Times", "Velocityms", "FractureHeightFromSrcm"];
opts.VariableTypes = ["double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
tbl = readtable(filename, opts);

%% Convert to output type
FractureHeightm = tbl.FractureHeightm;
Times = tbl.Times;
Velocityms = tbl.Velocityms;
FractureHeightFromSrcm=tbl.FractureHeightFromSrcm;
end