% -------------------------------------------------------------------
%  Generated by MATLAB on 28-Jul-2021 18:28:29
%  MATLAB version: 9.8.0.1396136 (R2020a) Update 3
% -------------------------------------------------------------------
saveVarsMat = load('PyFracSim2_Time21600.mat');

widths = saveVarsMat.widths; % <12425x1 double> too many elements

x = saveVarsMat.x; % <12425x1 double> too many elements

y = saveVarsMat.y; % <12425x1 double> too many elements

clear saveVarsMat;
