function [Time, x, z, vx, vz, Velocity] = importDelphineData2(filename, dataLines)
%IMPORTFILE Import data from a text file
%  [TIME, X, Z, VX, VZ, VELOCITY] = IMPORTFILE(FILENAME) reads data from
%  text file FILENAME for the default selection.  Returns the data as
%  column vectors.
%
%  [TIME, X, Z, VX, VZ, VELOCITY] = IMPORTFILE(FILE, DATALINES) reads
%  data for the specified row interval(s) of text file FILENAME. Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  [Time, x, z, vx, vz, Velocity] = importfile("C:\Users\eart0546\Downloads\VelocityData\M50-1945\data.txt", [1, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 28-Feb-2022 18:52:36

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [1, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 6);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Time", "x", "z", "vx", "vz", "Velocity"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
tbl = readtable(filename, opts);

%% Convert to output type
Time = tbl.Time;
x = tbl.x;
z = tbl.z;
vx = tbl.vx;
vz = tbl.vz;
Velocity = tbl.Velocity;
end